### ISSUE TITLE
NMR Hydrogen Coupling

### ISSUE THREAD

**Issue by SongXia-NYU** [microsoft/AI2BMD#14]
Congratulations on your excellent work! I am very interested in your research and would like to inquire if it would be possible to access the script used to calculate the NMR coupling from the trajectory data, specifically for reproducing **Figure 3e**. Your assistance would be greatly appreciated. Thank you!

**Comment by ElwynWang** [comment]
Please check the "Method" part and employ Karplus equation for the calculation.
