### ISSUE TITLE
Where can we get the original trajectory of the pdbs in article "https://www.nature.com/articles/s41586-024-08127-z#data-availability"

### ISSUE THREAD

**Issue by Eipgen** [microsoft/AI2BMD#18]
Dear Developers, your article shows you have computed DFT results of pdbs like chignolin: [5AWL](https://doi.org/10.2210/pdb5AWL/pdb); Trp-cage: [2JOF](https://doi.org/10.2210/pdb2JOF/pdb); WW domain: [2F21](https://doi.org/10.2210/pdb2F21/pdb); albumin-binding domain: [1PRB](https://doi.org/10.2210/pdb1PRB/pdb); PACSIN3, but I can't find the DFT results.

-  where can we get the trajectory with DFT labels? (need geometry and energy),

**Comment by ElwynWang** [comment]
The trajectories and DFT labels can be easily accessed by the following steps. For each kind of protein, downloading the protein structures from PDB (I think you've already done) and then performing replica exchange MD simulations on them, respectively. We also provide the PDB files for Chignilin, trp-cage and WW in the GitHub repo. You can use them as the initial structures. During the simulation, each replica ran for 2 ps before exchanging with neighbouring temperatures and 5,000 exchanges occurred in each production run. REMD trajectories were divided into three states according to the Cα RMSD against the crystal structure. Specifically, for chignolin, the folding structures have an RMSD of 0–2.5 Å, the intermediate structures have an RMSD of 2.5–7.5 Å, and the unfolding structures have an RMSD of more than 7.5 Å. For other proteins, the ranges of the three states are 0–5 Å, 5–15 Å and >15 Å. Then, folding and unfolding states should be further divided into 5 clusters, and the intermediate structures should be divided into 10 clusters via the CPPTRAJ ‘cluster’ program. To pick the structures of each cluster centre, accumulating 20 initial structures in total. Finally, each initial structure should be solvated in a 5-Å TIP3P water box (or you can try a larger one) and encountered 10 steps of 1-fs AI2BMD simulation. Simulations are carried out under an NVT ensemble. The simulation temperature (300 K) is controlled by a Berendsen thermostat and τ was 10 fs. The reference energy and force of the corresponding structures are calculated at the M06-2X–6-31g* level.
