### ISSUE TITLE
Question about how to train the machine learning potential for AI2BMD

### ISSUE THREAD

**Issue by zengdashi** [microsoft/AI2BMD#19]
I notice that there is a visnet mode in AI2BMD, and the doc says: "When using this mode, you need to train ViSNet model with the data of the molecules by yourself, upload the model to src/ViSNet and give the corresponding value to the argument ckpt-type. In this way, you can use AI(2)BMD simulation program to simulate any kinds of molecules beyond proteins. "

I would like to know if I need to train a machine learning potential for some specific amino acids or small molecules, what kind of data do I need to train the model?
Is it a database containing a large number of small molecules/non-standard amino acids or a database of results from DFT calculations on specific small molecules/non-standard amino acids?

**Comment by ElwynWang** [comment]
The model checkpoint provided in the repo was trained on Protein Dipeptide Dataset for standard amino acids. AIMD-Chig, QM9, MD17, MD22 and so on are some widely used datasets calculated at DFT level. If you'd like to generate the dataset by yourself, I suggest you to calculate energy and force by performing quantum simulation at DFT level (M06-2X/6-31g* or B3LYP-D3/6-31g*at least). For the pipeline to sample whole conformational space of a molecule at DFT level, you can take the paper https://www.nature.com/articles/s41597-023-02465-9 as a reference.

**Comment by ElwynWang** [comment]
The model checkpoint provided in this repo was trained on dipeptides with standard amino acids. If you'd like to perform simulations for small molecules and non-standard amino acids, you'd better to train the model with the such molecules (joint training with Protein Dipeptide Dataset or separately training is both fine).

**Comment by zengdashi** [comment]
Thank you very much for your reply!
