### ISSUE TITLE
Can this program be run without Docker in a non-root user environment?

### ISSUE THREAD

**Issue by CellLz** [microsoft/AI2BMD#20]
Since the computing platforms we use generally do not support root permissions and Docker deployment is not possible, is there a way to run this program without Docker in a non-root user environment?
Thank you very much for your guidance or help, I am extremely grateful!
（因为我们所使用的计算平台一般不支持root权限，并且也无法进行docker部署，请问有没有办法在非root用户的环境中不使用docker运行此程序呢？
非常感谢您能给予指导或帮助，万分感谢！）

**Comment by ElwynWang** [comment]
You can use the Docker without root permission (see the detailed settings in the Advanced Setup section). The environment setting is too complicated to ensure each user can setup well. To avoid any unexpected errors and incorrect software versions, currently we provide Docker, the simplest way to use it.
