### ISSUE TITLE
protein with ligand

### ISSUE THREAD

**Issue by Jinhui-Feng** [microsoft/AI2BMD#21]
Surprise! 
Does it possible to run a complex, including protein and a small molecular ligand?

**Comment by CellLz** [comment]
Currently, it is not possible to handle chemical structures other than amino acids, but if the next step can incorporate potential parameters for other small molecules, it should be possible to address the dynamics of small molecules and proteins within this framework.
![Image](https://github.com/user-attachments/assets/af90ecae-4a9d-4a5f-9887-3b1a81f1f3d1)
