### ISSUE TITLE
Provide environment file or docker container to install and run ViSNet?

### ISSUE THREAD

**Issue by sarmaier** [microsoft/AI2BMD#23]
Hello! I have been trying to install and train VisNet (using the VisNet branch), but have been having trouble with dependencies. Would it be possible to upload a relevant environment.yml file or a docker container to properly install and run this code? Thanks so much for all your work so far!

**Comment by sarmaier** [comment]
I realized I needed to downgrade pip and downgrade MKL. Thanks!

**Comment by CellLz** [comment]
Just need to
`docker pull ghcr.io/microsoft/ai2bmd:latest`
Then enter the container to run
`conda activate base`
You will get all the environment variables.
You need to use conda to manage the dependency, rather than pip.
