### ISSUE TITLE
singularity

### ISSUE THREAD

**Issue by gaoxiangcao** [microsoft/AI2BMD#24]
Hi developer，
Can i use this software in singularity cluster environment？

**Comment by CellLz** [comment]
This mainly depends on whether the server administrator provides systemctl and namespace permissions; if not, running rootless-Docker is useless.

**Comment by wewewexiao2008** [comment]
I have tried using Singularity. The cluster administrator helped me convert the Docker image to a .sif image. I then adapted an ai2bmd.py script for this purpose, mainly modifying some Docker-related commands. I used this command to run it:
`./ai2bmd-sif --prot-file chig.pdb --preprocess-dir chig_preprocessed --preeq-steps 0 --sim-steps 1000 --record-per-steps 1 --sif-path ./ai2bmd_latest.sif`

For ai2bmd-sif.py, please replace xxx in this line:
`launch_cmd = f"singularity exec --pwd {docker_cwd} {cat(gpu_opts)} {cat(mount_opts)} {sif_path} /opt/conda/bin/python -u /mnt/xxxx/AI2BMD/src/main.py {cat(argv)}"`
with the correct mount directory to use your cloned AI2BMD repository on the disk.

ai2bmd-sif.py

```python
#!/usr/bin/env python3
import argparse
import os
import subprocess
import sys
from os import path as osp
from pathlib import Path

_sif_image = "docker://ghcr.io/microsoft/ai2bmd:latest"
_sif_image_data = [f"docker://ghcr.io/microsoft/ai2bmd:training-data{i}" for i in range(1, 7)]
_src_dir = "/ai2bmd"

def parse_args(argv):
    # original arguments
    parser = argparse.ArgumentParser(description="DL Molecular Simulation.")
    parser.add_argument("--base-dir", type=str, default=os.getcwd(), help="A directory for running simulation")
    parser.add_argument("--log-dir", type=str, default=None, help="A directory for saving results")
    parser.add_argument("--src-dir", type=str, default=None, help="Use source code from local directory")
    parser.add_argument("--preprocess-dir", type=str, default=None, help="Use preprocessed protein files from local directory")
    parser.add_argument("--ckpt-path", type=str, default=osp.join(_src_dir, "ViSNet/checkpoints"), help="A directory including well-trained pytorch models")
    parser.add_argument("--ckpt-type", type=str, default="2ef43f29ec78fa5fef0b3de832bfada9", choices=["2ef43f29ec78fa5fef0b3de832bfada9"], help="Checkpoint type, which is the md5sum of the model checkpoint file")
    parser.add_argument("--prot-file", type=str, required=True, help="Protein file for simulation")
    parser.add_argument("--temp-k", type=int, default=300, help="Simulation temperature in Kelvin")
    parser.add_argument("--timestep", type=float, default=1, help="TimeStep (fs) for simulation")
    parser.add_argument("--sim-steps", type=int, default=100, help="Simulation steps for simulation")
    parser.add_argument("--preeq-steps", type=int, default=100, help="Pre-equilibration simulation steps for each constraint")
    parser.add_argument("--max-cyc", type=int, default=100, help="Maximum energy minimization cycles in preprocessing")
    parser.add_argument("--constraints", action='store_true', help="Constrain hydrogen bonds")
    parser.add_argument("--no-constraints", action='store_false', dest='constraints', help="Do not constrain hydrogen bonds")
    parser.add_argument("--solvent", action='store_true', help="Use solvent")
    parser.add_argument("--no-solvent", action='store_false', dest='solvent', help="Do not use solvent")
    parser.add_argument("--preprocess-method", type=str, default="FF19SB", choices=["FF19SB", "AMOEBA"], help="Method to use for preprocessing the protein")
    parser.add_argument("--mm-method", type=str, default="tinker-GPU", choices=["tinker", "tinker-GPU"], help="MM calculator for the nonbonded energy")
    parser.add_argument("--mode", type=str, default="fragment", choices=["fragment", "visnet"], help="Mode for performing calculations. fragment=Perform fragmentation (>1 amino acids in chain). visnet=Feed the input directly to ViSNet.")
    parser.add_argument("--fragment-longrange-calc", type=str, default="mm", choices=["mm", "pme"], help="Nonbonded calculator for fragments; required for 'fragment' mode.")
    parser.add_argument("--seed", type=int, default=0, help="Random seed for simulation")
    parser.add_argument("--restart", action='store_true', help="Restart the simulation")
    parser.add_argument("--no-restart", action='store_false', dest='restart', help="Do not restart the simulation")
    parser.add_argument("--build-frames", action='store_true', help="Build xyz frames from the trajectory after simulation")
    parser.add_argument("--no-build-frames", action='store_false', dest='build_frames', help="Do not build xyz frames from the trajectory")
    parser.add_argument("--record-per-steps", type=int, default=100, help="Interval for writing out frame data")
    parser.add_argument("--device-strategy", type=str, default="small-molecule", choices=["excess-compute", "small-molecule", "large-molecule"], help="The compute device allocation strategy.")
    parser.add_argument("--work-strategy", type=str, default="combined", choices=["combined"], help="The work allocation strategy.")
    parser.add_argument("--chunk-size", type=int, default=9999, help="Define the maximum chunk size (in units of atoms) for ACE-NME/dipeptide fragments.")
    parser.add_argument("-v", "--verbose", action='count', default=0, help="Verbosity level")
    parser.add_argument("--software-update", action='store_true', help="When specified, updates the program before running.")
    parser.add_argument("--download-training-data", action='store_true', help="When specified, downloads the AI2BMD training data, and unpacks it in the working directory. Ignores all other options.")
    parser.add_argument("--gpus", type=str, default=None, help="Specifies the GPU devices to passthrough to the program.")
    parser.add_argument("--sif-path", type=str, default=None, help="Path to existing .sif file. If not specified, will use default location in ~/.singularity/cache/")
    parser.add_argument("--dry-run", action='store_true', help="Only print the singularity command without executing it")
    return parser.parse_args(argv)

def rewrite_argv(argv, key, value):
    try:
        argv[argv.index(key)+1] = value
    except ValueError:
        argv.append(key)
        argv.append(value)

def remove_argv(argv, key, n):
    try:
        idx = argv.index(key)
        for _ in range(n):
            argv.pop(idx)
    except ValueError:
        pass

def check_env(cmd, message, do_exit=True):
    try:
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode == 0:
            return True
    except FileNotFoundError:
        pass
    print(message)
    if do_exit:
        sys.exit(-1)
    else:
        return False

def cat(args):
    return ' '.join(args)

def run(msg, cmd):
    print(msg)
    ret = os.system(cmd)
    if ret != 0:
        print('An error occurred when running the command, aborting.')
        exit(ret)

def main() -> None:
    argv = sys.argv[1:]

    # download training data
    if "--download-training-data" in argv:
        cache_dir = Path.home() / ".singularity/cache"
        cache_dir.mkdir(parents=True, exist_ok=True)
        
        for i, image in enumerate(_sif_image_data, 1):
            run(f'>>> Downloading AI2BMD training data part {i}...',
                f"singularity pull {cache_dir}/ai2bmd_data{i}.sif {image}")
            
            run(f'>>> Unpacking data part {i}...',
                f"singularity exec {cache_dir}/ai2bmd_data{i}.sif tar xJf /ai2bmd-training-part-{i}.tar.xz")
            
            run(f'>>> Cleaning up part {i}...',
                f"rm {cache_dir}/ai2bmd_data{i}.sif")
        
        print('>>> Done.')
        exit(0)

    args = parse_args(argv)

    # 0. health check
    check_env(['singularity', '--version'], 
              "Singularity is not installed. Please see https://sylabs.io/guides/latest/user-guide/quick_start.html for installation instructions.")
    
    gpu_ok = check_env(['nvidia-smi'], 
                       "NVIDIA driver is not installed or not properly loaded.", False)

    # 1. check for update
    remove_argv(argv, "--software-update", 1)
    if args.software_update:
        os.system(f"singularity pull {_sif_image}")

    # 2. get mount paths and rewrite args
    # 2a. cwd
    cwd = osp.abspath(os.getcwd())
    mount_paths = [cwd]
    docker_cwd = "/mnt" + cwd  # keep the same path mapping as Docker

    # 2b. base dir
    base_dir = osp.abspath(args.base_dir)
    mount_paths.append(base_dir)
    rewrite_argv(argv, "--base-dir", "/mnt" + base_dir)

    # 2c. log dir
    if args.log_dir is not None:
        log_dir = osp.abspath(args.log_dir)
        mount_paths.append(log_dir)
        rewrite_argv(argv, "--log-dir", "/mnt" + log_dir)

    # 2d. protein file dir
    prot_file = osp.abspath(args.prot_file)
    prot_dir = osp.dirname(prot_file)
    mount_paths.append(prot_dir)
    rewrite_argv(argv, "--prot-file", "/mnt" + prot_file)

    # prepare Singularity bind options
    mount_opts = []
    mount_paths.sort()
    for i, mp in enumerate(mount_paths):
        subdir = False
        for j in range(0, i):
            if mp.startswith(mount_paths[j]):
                subdir = True
                break
        if not subdir:
            mount_opts.extend(['--bind', f'{mp}:/mnt{mp}'])

    # 2e. local src dir
    remove_argv(argv, "--src-dir", 2)
    if args.src_dir is not None:
        src_dir = osp.abspath(args.src_dir)
        mount_opts.extend(['--bind', f'{src_dir}:/ai2bmd'])

    # 2f. local preprocessed protein dir
    remove_argv(argv, "--preprocess-dir", 2)
    if args.preprocess_dir is not None:
        preprocess_dir = osp.abspath(args.preprocess_dir)
        mount_opts.extend(['--bind', 
                          f'{preprocess_dir}:/mnt{prot_dir}/{os.path.basename(prot_file[:-4])}_preprocessed'])

    # 3. GPU options
    remove_argv(argv, "--gpus", 2)
    gpu_opts = ['--nv'] if gpu_ok and (args.gpus != "none") else []

    # 4. launch program
    if args.sif_path:
        sif_path = Path(args.sif_path)
    else:
        sif_path = Path.home() / ".singularity/cache/ai2bmd_latest.sif"
        if not sif_path.exists():
            run('>>> Pulling Singularity image...', 
                f"singularity pull {sif_path} {_sif_image}")
    
    remove_argv(argv, "--sif-path", 2)

    launch_cmd = f"singularity exec --pwd {docker_cwd} {cat(gpu_opts)} {cat(mount_opts)} {sif_path} /opt/conda/bin/python -u /mnt/xxxx/AI2BMD/src/main.py {cat(argv)}"
    print(f"Launching AI2BMD with Singularity: {launch_cmd}")
    
    if args.dry_run:
        shell_cmd = f"singularity shell --pwd {docker_cwd} {cat(gpu_opts)} {cat(mount_opts)} {sif_path}"
        print(f"\nTo enter the container with the same configuration, run:\n{shell_cmd}")
    else:
        os.system(launch_cmd)

if __name__ == "__main__":
    main()

```

**Comment by ElwynWang** [comment]
> I also ran into an issue while trying to use Singularity for running AI2BMD on a HPC cluster. After getting help from the cluster admin to convert the Docker image to a .sif format, I adapted the `ai2bmd.py` script for Singularity usage. Here's what I did:
> 
> 1. Modified Docker-specific commands in ./ai2bmd-sif to work with Singularity
> 2. Used this command to run:
> 
> ./ai2bmd-sif --prot-file chig.pdb --preprocess-dir chig_preprocessed --preeq-steps 0 --sim-steps 1000 --record-per-steps 1 --sif-path ./ai2bmd_latest.sif
> However, there's one thing that needs to be modified in the `ai2bmd-sif.py` script. In this line:
> 
> launch_cmd = f"singularity exec --pwd {docker_cwd} {cat(gpu_opts)} {cat(mount_opts)} {sif_path} /opt/conda/bin/python -u /mnt/xxxx/AI2BMD/src/main.py {cat(argv)}"
> You need to replace `xxxx` with the correct mount directory path where your cloned AI2BMD repository is located on disk.
> 
> ai2bmd-sif.py
> 
> #!/usr/bin/env python3
> import argparse
> import os
> import subprocess
> import sys
> from os import path as osp
> from pathlib import Path
> 
> _sif_image = "docker://ghcr.io/microsoft/ai2bmd:latest"
> _sif_image_data = [f"docker://ghcr.io/microsoft/ai2bmd:training-data{i}" for i in range(1, 7)]
> _src_dir = "/ai2bmd"
> 
> def parse_args(argv):
>     # original arguments
>     parser = argparse.ArgumentParser(description="DL Molecular Simulation.")
>     parser.add_argument("--base-dir", type=str, default=os.getcwd(), help="A directory for running simulation")
>     parser.add_argument("--log-dir", type=str, default=None, help="A directory for saving results")
>     parser.add_argument("--src-dir", type=str, default=None, help="Use source code from local directory")
>     parser.add_argument("--preprocess-dir", type=str, default=None, help="Use preprocessed protein files from local directory")
>     parser.add_argument("--ckpt-path", type=str, default=osp.join(_src_dir, "ViSNet/checkpoints"), help="A directory including well-trained pytorch models")
>     parser.add_argument("--ckpt-type", type=str, default="2ef43f29ec78fa5fef0b3de832bfada9", choices=["2ef43f29ec78fa5fef0b3de832bfada9"], help="Checkpoint type, which is the md5sum of the model checkpoint file")
>     parser.add_argument("--prot-file", type=str, required=True, help="Protein file for simulation")
>     parser.add_argument("--temp-k", type=int, default=300, help="Simulation temperature in Kelvin")
>     parser.add_argument("--timestep", type=float, default=1, help="TimeStep (fs) for simulation")
>     parser.add_argument("--sim-steps", type=int, default=100, help="Simulation steps for simulation")
>     parser.add_argument("--preeq-steps", type=int, default=100, help="Pre-equilibration simulation steps for each constraint")
>     parser.add_argument("--max-cyc", type=int, default=100, help="Maximum energy minimization cycles in preprocessing")
>     parser.add_argument("--constraints", action='store_true', help="Constrain hydrogen bonds")
>     parser.add_argument("--no-constraints", action='store_false', dest='constraints', help="Do not constrain hydrogen bonds")
>     parser.add_argument("--solvent", action='store_true', help="Use solvent")
>     parser.add_argument("--no-solvent", action='store_false', dest='solvent', help="Do not use solvent")
>     parser.add_argument("--preprocess-method", type=str, default="FF19SB", choices=["FF19SB", "AMOEBA"], help="Method to use for preprocessing the protein")
>     parser.add_argument("--mm-method", type=str, default="tinker-GPU", choices=["tinker", "tinker-GPU"], help="MM calculator for the nonbonded energy")
>     parser.add_argument("--mode", type=str, default="fragment", choices=["fragment", "visnet"], help="Mode for performing calculations. fragment=Perform fragmentation (>1 amino acids in chain). visnet=Feed the input directly to ViSNet.")
>     parser.add_argument("--fragment-longrange-calc", type=str, default="mm", choices=["mm", "pme"], help="Nonbonded calculator for fragments; required for 'fragment' mode.")
>     parser.add_argument("--seed", type=int, default=0, help="Random seed for simulation")
>     parser.add_argument("--restart", action='store_true', help="Restart the simulation")
>     parser.add_argument("--no-restart", action='store_false', dest='restart', help="Do not restart the simulation")
>     parser.add_argument("--build-frames", action='store_true', help="Build xyz frames from the trajectory after simulation")
>     parser.add_argument("--no-build-frames", action='store_false', dest='build_frames', help="Do not build xyz frames from the trajectory")
>     parser.add_argument("--record-per-steps", type=int, default=100, help="Interval for writing out frame data")
>     parser.add_argument("--device-strategy", type=str, default="small-molecule", choices=["excess-compute", "small-molecule", "large-molecule"], help="The compute device allocation strategy.")
>     parser.add_argument("--work-strategy", type=str, default="combined", choices=["combined"], help="The work allocation strategy.")
>     parser.add_argument("--chunk-size", type=int, default=9999, help="Define the maximum chunk size (in units of atoms) for ACE-NME/dipeptide fragments.")
>     parser.add_argument("-v", "--verbose", action='count', default=0, help="Verbosity level")
>     parser.add_argument("--software-update", action='store_true', help="When specified, updates the program before running.")
>     parser.add_argument("--download-training-data", action='store_true', help="When specified, downloads the AI2BMD training data, and unpacks it in the working directory. Ignores all other options.")
>     parser.add_argument("--gpus", type=str, default=None, help="Specifies the GPU devices to passthrough to the program.")
>     parser.add_argument("--sif-path", type=str, default=None, help="Path to existing .sif file. If not specified, will use default location in ~/.singularity/cache/")
>     parser.add_argument("--dry-run", action='store_true', help="Only print the singularity command without executing it")
>     return parser.parse_args(argv)
> 
> def rewrite_argv(argv, key, value):
>     try:
>         argv[argv.index(key)+1] = value
>     except ValueError:
>         argv.append(key)
>         argv.append(value)
> 
> def remove_argv(argv, key, n):
>     try:
>         idx = argv.index(key)
>         for _ in range(n):
>             argv.pop(idx)
>     except ValueError:
>         pass
> 
> def check_env(cmd, message, do_exit=True):
>     try:
>         result = subprocess.run(cmd, capture_output=True, text=True)
>         if result.returncode == 0:
>             return True
>     except FileNotFoundError:
>         pass
>     print(message)
>     if do_exit:
>         sys.exit(-1)
>     else:
>         return False
> 
> def cat(args):
>     return ' '.join(args)
> 
> def run(msg, cmd):
>     print(msg)
>     ret = os.system(cmd)
>     if ret != 0:
>         print('An error occurred when running the command, aborting.')
>         exit(ret)
> 
> def main() -> None:
>     argv = sys.argv[1:]
> 
>     # download training data
>     if "--download-training-data" in argv:
>         cache_dir = Path.home() / ".singularity/cache"
>         cache_dir.mkdir(parents=True, exist_ok=True)
>         
>         for i, image in enumerate(_sif_image_data, 1):
>             run(f'>>> Downloading AI2BMD training data part {i}...',
>                 f"singularity pull {cache_dir}/ai2bmd_data{i}.sif {image}")
>             
>             run(f'>>> Unpacking data part {i}...',
>                 f"singularity exec {cache_dir}/ai2bmd_data{i}.sif tar xJf /ai2bmd-training-part-{i}.tar.xz")
>             
>             run(f'>>> Cleaning up part {i}...',
>                 f"rm {cache_dir}/ai2bmd_data{i}.sif")
>         
>         print('>>> Done.')
>         exit(0)
> 
>     args = parse_args(argv)
> 
>     # 0. health check
>     check_env(['singularity', '--version'], 
>               "Singularity is not installed. Please see https://sylabs.io/guides/latest/user-guide/quick_start.html for installation instructions.")
>     
>     gpu_ok = check_env(['nvidia-smi'], 
>                        "NVIDIA driver is not installed or not properly loaded.", False)
> 
>     # 1. check for update
>     remove_argv(argv, "--software-update", 1)
>     if args.software_update:
>         os.system(f"singularity pull {_sif_image}")
> 
>     # 2. get mount paths and rewrite args
>     # 2a. cwd
>     cwd = osp.abspath(os.getcwd())
>     mount_paths = [cwd]
>     docker_cwd = "/mnt" + cwd  # keep the same path mapping as Docker
> 
>     # 2b. base dir
>     base_dir = osp.abspath(args.base_dir)
>     mount_paths.append(base_dir)
>     rewrite_argv(argv, "--base-dir", "/mnt" + base_dir)
> 
>     # 2c. log dir
>     if args.log_dir is not None:
>         log_dir = osp.abspath(args.log_dir)
>         mount_paths.append(log_dir)
>         rewrite_argv(argv, "--log-dir", "/mnt" + log_dir)
> 
>     # 2d. protein file dir
>     prot_file = osp.abspath(args.prot_file)
>     prot_dir = osp.dirname(prot_file)
>     mount_paths.append(prot_dir)
>     rewrite_argv(argv, "--prot-file", "/mnt" + prot_file)
> 
>     # prepare Singularity bind options
>     mount_opts = []
>     mount_paths.sort()
>     for i, mp in enumerate(mount_paths):
>         subdir = False
>         for j in range(0, i):
>             if mp.startswith(mount_paths[j]):
>                 subdir = True
>                 break
>         if not subdir:
>             mount_opts.extend(['--bind', f'{mp}:/mnt{mp}'])
> 
>     # 2e. local src dir
>     remove_argv(argv, "--src-dir", 2)
>     if args.src_dir is not None:
>         src_dir = osp.abspath(args.src_dir)
>         mount_opts.extend(['--bind', f'{src_dir}:/ai2bmd'])
> 
>     # 2f. local preprocessed protein dir
>     remove_argv(argv, "--preprocess-dir", 2)
>     if args.preprocess_dir is not None:
>         preprocess_dir = osp.abspath(args.preprocess_dir)
>         mount_opts.extend(['--bind', 
>                           f'{preprocess_dir}:/mnt{prot_dir}/{os.path.basename(prot_file[:-4])}_preprocessed'])
> 
>     # 3. GPU options
>     remove_argv(argv, "--gpus", 2)
>     gpu_opts = ['--nv'] if gpu_ok and (args.gpus != "none") else []
> 
>     # 4. launch program
>     if args.sif_path:
>         sif_path = Path(args.sif_path)
>     else:
>         sif_path = Path.home() / ".singularity/cache/ai2bmd_latest.sif"
>         if not sif_path.exists():
>             run('>>> Pulling Singularity image...', 
>                 f"singularity pull {sif_path} {_sif_image}")
>     
>     remove_argv(argv, "--sif-path", 2)
> 
>     launch_cmd = f"singularity exec --pwd {docker_cwd} {cat(gpu_opts)} {cat(mount_opts)} {sif_path} /opt/conda/bin/python -u /mnt/xxxx/AI2BMD/src/main.py {cat(argv)}"
>     print(f"Launching AI2BMD with Singularity: {launch_cmd}")
>     
>     if args.dry_run:
>         shell_cmd = f"singularity shell --pwd {docker_cwd} {cat(gpu_opts)} {cat(mount_opts)} {sif_path}"
>         print(f"\nTo enter the container with the same configuration, run:\n{shell_cmd}")
>     else:
>         os.system(launch_cmd)
> 
> if __name__ == "__main__":
>     main()

Thanks to provide the solution. This will be useful for others.
