### ISSUE TITLE
[Errno 32] Broken pipe, while trying to run chignolin demo

### ISSUE THREAD

**Issue by AugMark** [microsoft/AI2BMD#25]
I get an Errno 32 Broken Pipe error while trying to run the chignolin demo simulation. Here is the complete terminal output:

sudo ./ai2bmd --prot-file chig.pdb --preprocess-dir chig_preprocessed --preeq-steps 0 --sim-steps 1000 --record-per-steps 1
Launching AI2BMD with Docker: docker run -w /mnt/home/augustas/OneDrive/VU/Bakalauras/Ai2BMD --gpus all --rm -v /home/augustas/OneDrive/VU/Bakalauras/Ai2BMD:/mnt/home/augustas/OneDrive/VU/Bakalauras/Ai2BMD -v /home/augustas/OneDrive/VU/Bakalauras/Ai2BMD/chig_preprocessed:/mnt/home/augustas/OneDrive/VU/Bakalauras/Ai2BMD/chig_preprocessed ghcr.io/microsoft/ai2bmd:latest python -u /ai2bmd/main.py --prot-file /mnt/home/augustas/OneDrive/VU/Bakalauras/Ai2BMD/chig.pdb --preeq-steps 0 --sim-steps 1000 --record-per-steps 1 --base-dir /mnt/home/augustas/OneDrive/VU/Bakalauras/Ai2BMD
DeviceStrategy: setting strategy to [small-molecule / combined]
Preprocessing step already done, skip...
run_preprocess takes 0.0034914016723632812 seconds
Loading models...
Start simulation for 1000 steps
[Errno 32] Broken pipe
[Errno 32] Broken pipe
[Errno 32] Broken pipe
[Errno 32] Broken pipe
[Errno 32] Broken pipe
[Errno 32] Broken pipe
*^This line gets repeated multiple times more^*
Solvent dynamic component Tinker terminated abnormally, cannot proceed.

Any ideas as to why this error occurs? My operating system is Linux Debian Bookworm. My router and firewall settings are default and the docker pull from the installation/configuration steps worked without issue.

**Comment by AugMark** [comment]
I can run the command without sudo, but it gives the same Errno 52 Broken Pipe error.

My CPU is an AMD Ryzen 5 3600 6 Core. My GPU is an Nvidia GeForce GTX 970. I also have 16 GB of RAM on this computer

**Comment by zhachao2010** [comment]
I also get the same Error when my gpu device is P6000. It works after I change to V100 or A100.

**Comment by ElwynWang** [comment]
Ensure the GPU you used is in the support list (see README)
