### ISSUE TITLE
Pre-equilibration stage is extremely slow

### ISSUE THREAD

**Issue by zhachao2010** [microsoft/AI2BMD#26]
Congratulations on your Nature publication! it's an incredibly solid and impressive piece of work! 

I'm attempting to simulate a protein structure of around 200–300 amino acids using default parameters. However, I noticed that the pre-equilibration stage is extremely slow—it's been running for over ten hours. I’m wondering if this is typical. Are there any optimization methods or adjustable parameters that could help speed up this process? 

I'd greatly appreciate your advice. Thank you!

**Comment by Frank-LIU-520** [comment]
How do you set the  pre-equilibration stage parameters? Could you show the command args please.

**Comment by zhachao2010** [comment]
Here's my command. 

sudo $(which python) ./ai2bmd --prot-file ../examples/originial_cap_process.pdb --preeq-steps 0 --sim-steps 1000 --record-per-steps 1 --base-dir test

The command is still running after almost 20 hours, and the output files 'preeq4.out' for Stage 4 are continuously updating, indicating that the program is still running normally.

**Comment by ElwynWang** [comment]
Please get Amber software license by yourself, use the parallel and GPU-support version of sander or pmemd and modify the code accordingly. With parallel computing, the preeq process will be completed in several minutes.
