### ISSUE TITLE
Simulation pause at about 80-100 step for chignolin

### ISSUE THREAD

**Issue by Frank-LIU-520** [microsoft/AI2BMD#27]
I followed the 'Get Start' instruction to run a MD for chignolin. However it can not proceed after about 80 steps with the warning **Solvent dynamic component Tinker terminated abnormally, cannot proceed.**. What should I do?

**Details:**
Command line: "./ai2bmd --prot-file chig.pdb --preprocess-dir chig_preprocessed --preeq-steps 0 --sim-steps 1000 --record-per-steps 1"
GPU: NVIDIA GeForce RTX 3090
OS: Ubuntu 20.04.6 LTS
Docker: Docker version 27.1.2

**OUTPUT**
DeviceStrategy: setting strategy to [small-molecule / combined]
_ERROR:root:tinker-GPU is specified, but there's no GPU. Reverting back to CPU_.
Preprocessing step already done, skip...
run_preprocess takes 0.2249157428741455 seconds
Loading models...
Start simulation for 1000 steps
Step 0: Epot = -129456.773eV Ekin = 688.941eV Etot = -128767.832eV
Step 1: Epot = -129495.345eV Ekin = 724.111eV Etot = -128771.234eV
Step 2: Epot = -129566.198eV Ekin = 789.967eV Etot = -128776.231eV
Step 3: Epot = -129598.216eV Ekin = 822.229eV Etot = -128775.987eV
Step 4: Epot = -129598.440eV Ekin = 825.653eV Etot = -128772.787eV
Step 5: Epot = -129612.714eV Ekin = 837.533eV Etot = -128775.182eV
Step 6: Epot = -129625.972eV Ekin = 847.866eV Etot = -128778.107eV
Step 7: Epot = -129596.541eV Ekin = 819.423eV Etot = -128777.118eV
Step 8: Epot = -129534.537eV Ekin = 761.545eV Etot = -128772.992eV
Step 9: Epot = -129501.501eV Ekin = 731.050eV Etot = -128770.452eV
Step 10: Epot = -129534.765eV Ekin = 761.559eV Etot = -128773.206eV
Step 11: Epot = -129599.201eV Ekin = 820.766eV Etot = -128778.434eV
Step 12: Epot = -129634.611eV Ekin = 855.326eV Etot = -128779.286eV
Step 13: Epot = -129640.745eV Ekin = 863.866eV Etot = -128776.878eV
Step 14: Epot = -129655.990eV Ekin = 877.433eV Etot = -128778.557eV
Step 15: Epot = -129672.862eV Ekin = 891.577eV Etot = -128781.285eV
Step 16: Epot = -129653.018eV Ekin = 871.709eV Etot = -128781.309eV
Step 17: Epot = -129594.452eV Ekin = 816.439eV Etot = -128778.013eV
Step 18: Epot = -129550.091eV Ekin = 775.125eV Etot = -128774.966eV
Step 19: Epot = -129566.279eV Ekin = 789.375eV Etot = -128776.904eV
Step 20: Epot = -129622.065eV Ekin = 840.169eV Etot = -128781.896eV
Step 21: Epot = -129655.988eV Ekin = 871.981eV Etot = -128784.006eV
Step 22: Epot = -129653.208eV Ekin = 871.409eV Etot = -128781.798eV
Step 23: Epot = -129654.457eV Ekin = 872.827eV Etot = -128781.631eV
Step 24: Epot = -129667.680eV Ekin = 883.595eV Etot = -128784.085eV
Step 25: Epot = -129657.169eV Ekin = 871.864eV Etot = -128785.305eV
Step 26: Epot = -129607.404eV Ekin = 824.785eV Etot = -128782.618eV
Step 27: Epot = -129555.005eV Ekin = 775.848eV Etot = -128779.156eV
Step 28: Epot = -129549.702eV Ekin = 770.331eV Etot = -128779.371eV
Step 29: Epot = -129592.846eV Ekin = 809.599eV Etot = -128783.247eV
Step 30: Epot = -129636.278eV Ekin = 849.728eV Etot = -128786.550eV
Step 31: Epot = -129646.069eV Ekin = 860.401eV Etot = -128785.669eV
Step 32: Epot = -129644.614eV Ekin = 859.336eV Etot = -128785.278eV
Step 33: Epot = -129655.668eV Ekin = 868.655eV Etot = -128787.013eV
Step 34: Epot = -129659.041eV Ekin = 870.171eV Etot = -128788.870eV
Step 35: Epot = -129626.131eV Ekin = 838.435eV Etot = -128787.697eV
Step 36: Epot = -129572.651eV Ekin = 788.652eV Etot = -128784.000eV
Step 37: Epot = -129553.920eV Ekin = 770.873eV Etot = -128783.047eV
Step 38: Epot = -129592.649eV Ekin = 806.418eV Etot = -128786.231eV
Step 39: Epot = -129647.119eV Ekin = 856.581eV Etot = -128790.538eV
Step 40: Epot = -129665.002eV Ekin = 874.198eV Etot = -128790.804eV
Step 41: Epot = -129654.542eV Ekin = 866.057eV Etot = -128788.484eV
Step 42: Epot = -129655.266eV Ekin = 866.516eV Etot = -128788.749eV
Step 43: Epot = -129663.942eV Ekin = 872.869eV Etot = -128791.073eV
Step 44: Epot = -129646.117eV Ekin = 854.610eV Etot = -128791.506eV
Step 45: Epot = -129596.400eV Ekin = 808.372eV Etot = -128788.028eV
Step 46: Epot = -129561.757eV Ekin = 775.902eV Etot = -128785.856eV
Step 47: Epot = -129579.735eV Ekin = 792.606eV Etot = -128787.129eV
Step 48: Epot = -129629.309eV Ekin = 838.175eV Etot = -128791.134eV
Step 49: Epot = -129659.307eV Ekin = 866.053eV Etot = -128793.255eV
Step 50: Epot = -129655.002eV Ekin = 862.626eV Etot = -128792.376eV
Step 51: Epot = -129648.746eV Ekin = 857.333eV Etot = -128791.413eV
Step 52: Epot = -129657.228eV Ekin = 863.275eV Etot = -128793.953eV
Step 53: Epot = -129653.428eV Ekin = 857.709eV Etot = -128795.719eV
Step 54: Epot = -129613.325eV Ekin = 820.299eV Etot = -128793.026eV
Step 55: Epot = -129569.882eV Ekin = 780.334eV Etot = -128789.548eV
Step 56: Epot = -129574.259eV Ekin = 784.853eV Etot = -128789.406eV
Step 57: Epot = -129623.452eV Ekin = 830.145eV Etot = -128793.307eV
Step 58: Epot = -129666.217eV Ekin = 869.955eV Etot = -128796.262eV
Step 59: Epot = -129668.508eV Ekin = 873.131eV Etot = -128795.378eV
Step 60: Epot = -129653.026eV Ekin = 859.035eV Etot = -128793.991eV
Step 61: Epot = -129653.227eV Ekin = 857.672eV Etot = -128795.556eV
Step 62: Epot = -129657.065eV Ekin = 859.225eV Etot = -128797.840eV
Step 63: Epot = -129631.260eV Ekin = 834.497eV Etot = -128796.763eV
Step 64: Epot = -129586.275eV Ekin = 793.560eV Etot = -128792.715eV
Step 65: Epot = -129572.147eV Ekin = 780.631eV Etot = -128791.516eV
Step 66: Epot = -129605.296eV Ekin = 810.945eV Etot = -128794.351eV
Step 67: Epot = -129649.955eV Ekin = 852.287eV Etot = -128797.668eV
Step 68: Epot = -129664.583eV Ekin = 866.057eV Etot = -128798.526eV
Step 69: Epot = -129651.364eV Ekin = 854.834eV Etot = -128796.529eV
Step 70: Epot = -129645.825eV Ekin = 849.377eV Etot = -128796.448eV
Step 71: Epot = -129651.242eV Ekin = 852.374eV Etot = -128798.868eV
Step 72: Epot = -129635.424eV Ekin = 836.037eV Etot = -128799.387eV
Step 73: Epot = -129593.856eV Ekin = 797.441eV Etot = -128796.415eV
Step 74: Epot = -129569.291eV Ekin = 775.070eV Etot = -128794.220eV
Step 75: Epot = -129592.963eV Ekin = 796.785eV Etot = -128796.177eV
Step 76: Epot = -129641.187eV Ekin = 840.996eV Etot = -128800.191eV
Step 77: Epot = -129666.154eV Ekin = 864.446eV Etot = -128801.708eV
Step 78: Epot = -129655.084eV Ekin = 854.900eV Etot = -128800.185eV
Step 79: Epot = -129642.137eV Ekin = 842.303eV Etot = -128799.834eV
Step 80: Epot = -129644.443eV Ekin = 842.619eV Etot = -128801.824eV
Step 81: Epot = -129636.401eV Ekin = 833.666eV Etot = -128802.735eV
Step 82: Epot = -129604.452eV Ekin = 803.856eV Etot = -128800.596eV
Step 83: Epot = -129575.009eV Ekin = 776.883eV Etot = -128798.126eV
Step 84: Epot = -129583.019eV Ekin = 784.694eV Etot = -128798.325eV
Step 85: Epot = -129622.924eV Ekin = 821.153eV Etot = -128801.771eV
Step 86: Epot = -129655.369eV Ekin = 851.102eV Etot = -128804.268eV
Step 87: Epot = -129655.577eV Ekin = 851.463eV Etot = -128804.115eV
Step 88: Epot = -129644.464eV Ekin = 840.994eV Etot = -128803.470eV
Step 89: Epot = -129644.259eV Ekin = 839.590eV Etot = -128804.668eV
**Solvent dynamic component Tinker terminated abnormally, cannot proceed.**
Launching AI2BMD with Docker: docker run -w /mnt/data2/home_data/ztliu/quantum --gpus all --rm -v /data2/home_data/ztliu/quantum:/mnt/data2/home_data/ztliu/quantum -v /data2/home_data/ztliu/quantum/chig_preprocessed:/mnt/data2/home_data/ztliu/quantum/chig_preprocessed ghcr.io/microsoft/ai2bmd:latest python -u /ai2bmd/main.py --prot-file /mnt/data2/home_data/ztliu/quantum/chig.pdb --preeq-steps 0 --sim-steps 1000 --record-per-steps 1 --base-dir /mnt/data2/home_data/ztliu/quantum

**Comment by Frank-LIU-520** [comment]
BTW, how can I set the tinker parameters in docker?

**Comment by Frank-LIU-520** [comment]
How can I set tinker-GPU to run this. I have tried the args '--gpus 4' but nothing happened. It is still running on cpu.

**Comment by ElwynWang** [comment]
The screen output says: ERROR:root:tinker-GPU is specified, but there's no GPU. Reverting back to CPU.
You should check whether the GPU is available and works well. There's no need to set any parameters in Docker. In addition, make sure to the GPU type is in the support list (see README)

**Comment by Frank-LIU-520** [comment]
I have made the GPU available and worked well accoding to the README support list. However, this issue doesn't dispear. It can't sustain for too long in real case dynamics.

**Comment by ElwynWang** [comment]
Has the error output disappeared? If not, you device setting still has problems. 
Furthermore, I don't believe RTX 3090 you used is in the support list.![Image](https://github.com/user-attachments/assets/b71a1ac7-d81a-41b5-86b6-88811e60202c)
As shown in the previous response, make sure to the GPU type is in the support list
