### ISSUE TITLE
Could you please provide the input files and tutorial of pKa calculation for Asp26 of thioredoxin ?

### ISSUE THREAD

**Issue by Frank-LIU-520** [microsoft/AI2BMD#28]
In the Extended Data Fig. 6, there are Comparison of pKa calculation for Asp26 of thioredoxin among AI2BMD and other approaches.
I wonder if you can provide all the inputs file, codes, and tutorial on how to implement this.

![Image](https://github.com/user-attachments/assets/2294b411-98b8-442b-abd1-05ec640a5c9d)

**Comment by ElwynWang** [comment]
You can check the technical details in the "Method" part of the paper and calculate the value accordingly.
