### ISSUE TITLE
Protein File Preparation and Misaligned

### ISSUE THREAD

**Issue by DaHenz** [microsoft/AI2BMD#29]
After pdb4amber, I can only get 

HETATM    1  C   ACE A   1      32.763  17.920  10.953  1.00  0.00           C  
HETATM    2  O   ACE A   1      31.579  18.240  11.127  1.00  0.00           O  
HETATM    3  CH3 ACE A   1      33.848  18.971  10.858  1.00  0.00           C  
HETATM    4  H1  ACE A   1      34.579  18.813  11.651  1.00  0.00           H  
HETATM    5  H2  ACE A   1      34.342  18.897   9.889  1.00  0.00           H  
HETATM    6  H3  ACE A   1      33.406  19.961  10.965  1.00  0.00           H
.....
HETATM 5228  N   NME A 343     -16.911  -9.321 -36.816  1.00  0.00           N  
HETATM 5229  CH3 NME A 343     -16.060 -10.370 -36.281  1.00  0.00           C  
HETATM 5230  HN2 NME A 343     -17.875  -9.313 -36.483  1.00  0.00           H  
HETATM 5231  H1  NME A 343     -16.634 -10.986 -35.589  1.00  0.00           H  
HETATM 5232  H2  NME A 343     -15.690 -10.990 -37.097  1.00  0.00           H  
HETATM 5233  H3  NME A 343     -15.217  -9.922 -35.755  1.00  0.00           H 

I need to change "NME" atom names manually  to 

HETATM 5228  N   NME A 343     -16.911  -9.321 -36.816  1.00  0.00           N  
HETATM 5229  CH3 NME A 343     -16.060 -10.370 -36.281  1.00  0.00           C  
HETATM 5230  H   NME A 343     -17.875  -9.313 -36.483  1.00  0.00           H  
HETATM 5231 HH31 NME A 343     -16.634 -10.986 -35.589  1.00  0.00           H  
HETATM 5232 HH32 NME A 343     -15.690 -10.990 -37.097  1.00  0.00           H  
HETATM 5233 HH33 NME A 343     -15.217  -9.922 -35.755  1.00  0.00           H 

However this still cause error after preprocessing:

```
 run_preprocess takes 50.503188371658325 seconds
Traceback (most recent call last):
  File "/ai2bmd/main.py", line 44, in <module>
    prot = Protein(read_protein(preeq_pdb), pdb4params=preeq_nowat_pdb)
  File "/ai2bmd/AIMD/protein.py", line 38, in __init__
    self.generate_nonbonded_params()
  File "/ai2bmd/AIMD/protein.py", line 157, in generate_nonbonded_params
    pdb = PDBFile(self.nowater_PDB_path)
  File "/opt/conda/lib/python3.9/site-packages/openmm/app/pdbfile.py", line 95, in __init__
    pdb = PdbStructure(inputfile, load_all_models=True, extraParticleIdentifier=extraParticleIdentifier)
  File "/opt/conda/lib/python3.9/site-packages/openmm/app/internal/pdbstructure.py", line 152, in __init__
    self._load(input_stream)
  File "/opt/conda/lib/python3.9/site-packages/openmm/app/internal/pdbstructure.py", line 164, in _load
    self._add_atom(Atom(pdb_line, self, self.extraParticleIdentifier))
  File "/opt/conda/lib/python3.9/site-packages/openmm/app/internal/pdbstructure.py", line 749, in __init__
    raise ValueError('Misaligned residue name: %s' % pdb_line)
ValueError: Misaligned residue name: ATOM       1  CH3 ACE    1      27.787  18.300  16.949
```

**Comment by Sunlong0v0** [comment]
Hello, I have encountered the same problem before. Perhaps your protein is too large, and there may be formatting errors in the subsequent files. Try replacing it with a smaller protein. For example, in my mistake, the coordinates of water in the balanced pdb file are like this. I think it may not exceed 99999 atoms, otherwise the recognition will be incorrect. I hope it can help you.

xxx-preeq.pdb：
HETATM125189  H   HOH 1523     -34.961 -34.225 -28.199
HETATM125190  O   HOH 1524     -30.797 -30.365 -44.612
HETATM125191  H   HOH 1524     -31.037 -30.907 -45.373
HETATM125192  H   HOH 1524     -30.473 -29.532 -44.973
HETATM125193  O   HOH 1525     -38.923 -34.691 -46.444

**Comment by Sunlong0v0** [comment]
@DaHenz  Hello, I have encountered the same problem before. Perhaps your protein is too large, and there may be formatting errors in the subsequent files. Try replacing it with a smaller protein. For example, in my mistake, the coordinates of water in the balanced pdb file are like this. I think it may not exceed 99999 atoms, otherwise the recognition will be incorrect. I hope it can help you.

xxx-preeq.pdb：
HETATM125189 H HOH 1523 -34.961 -34.225 -28.199
HETATM125190 O HOH 1524 -30.797 -30.365 -44.612
HETATM125191 H HOH 1524 -31.037 -30.907 -45.373
HETATM125192 H HOH 1524 -30.473 -29.532 -44.973
HETATM125193 O HOH 1525 -38.923 -34.691 -46.444

**Comment by DaHenz** [comment]
> [@DaHenz](https://github.com/DaHenz) Hello, I have encountered the same problem before. Perhaps your protein is too large, and there may be formatting errors in the subsequent files. Try replacing it with a smaller protein. For example, in my mistake, the coordinates of water in the balanced pdb file are like this. I think it may not exceed 99999 atoms, otherwise the recognition will be incorrect. I hope it can help you.
> 
> xxx-preeq.pdb： HETATM125189 H HOH 1523 -34.961 -34.225 -28.199 HETATM125190 O HOH 1524 -30.797 -30.365 -44.612 HETATM125191 H HOH 1524 -31.037 -30.907 -45.373 HETATM125192 H HOH 1524 -30.473 -29.532 -44.973 HETATM125193 O HOH 1525 -38.923 -34.691 -46.444

Hi, many thanks for your answer. I know this issue and think too much water is the reason for shifting the pdb register at preeq(also nowat) pdbs. However, my protein has only 5333 atoms, and in the publication, the AI2BMD can take Aminopeptidase-N which has 13728 atoms.

**Comment by DaHenz** [comment]
For large proteins (maybe > 300 AAs Or decide based on the specific volume), use a smaller box size (the default value is 20, in my case with a 350 AA-protein should this size be changed to 10.), which can be modified in the preprocessed script. Thanks all for your attention and discussions!

**Comment by Lyueyang2020** [comment]
> For large proteins (maybe > 300 AAs Or decide based on the specific volume), use a smaller box size (the default value is 20, in my case with a 350 AA-protein should this size be changed to 10.), which can be modified in the preprocessed script. Thanks all for your attention and discussions!

How did you get the changed preprocess.py file to run successfully?
When I download your entire project locally, after modifying only my local src/AIMD/preprocess.py (pmemd.cuda), it's still the initial preprocess.py (sander) that is run using docker. I'm not quite sure how to run the Docker container pointing to my modified preprocess.py file
e.g. the command “docker cp c8e80ad4aacf:/path/to/container/file.txt /path/to/local/directory/”
And I'm not quite sure about container folder path.

**Comment by Lyueyang2020** [comment]
> After pdb4amber, I can only get
> 
> HETATM 1 C ACE A 1 32.763 17.920 10.953 1.00 0.00 C HETATM 2 O ACE A 1 31.579 18.240 11.127 1.00 0.00 O HETATM 3 CH3 ACE A 1 33.848 18.971 10.858 1.00 0.00 C HETATM 4 H1 ACE A 1 34.579 18.813 11.651 1.00 0.00 H HETATM 5 H2 ACE A 1 34.342 18.897 9.889 1.00 0.00 H HETATM 6 H3 ACE A 1 33.406 19.961 10.965 1.00 0.00 H ..... HETATM 5228 N NME A 343 -16.911 -9.321 -36.816 1.00 0.00 N HETATM 5229 CH3 NME A 343 -16.060 -10.370 -36.281 1.00 0.00 C HETATM 5230 HN2 NME A 343 -17.875 -9.313 -36.483 1.00 0.00 H HETATM 5231 H1 NME A 343 -16.634 -10.986 -35.589 1.00 0.00 H HETATM 5232 H2 NME A 343 -15.690 -10.990 -37.097 1.00 0.00 H HETATM 5233 H3 NME A 343 -15.217 -9.922 -35.755 1.00 0.00 H
> 
> I need to change "NME" atom names manually to
> 
> HETATM 5228 N NME A 343 -16.911 -9.321 -36.816 1.00 0.00 N HETATM 5229 CH3 NME A 343 -16.060 -10.370 -36.281 1.00 0.00 C HETATM 5230 H NME A 343 -17.875 -9.313 -36.483 1.00 0.00 H HETATM 5231 HH31 NME A 343 -16.634 -10.986 -35.589 1.00 0.00 H HETATM 5232 HH32 NME A 343 -15.690 -10.990 -37.097 1.00 0.00 H HETATM 5233 HH33 NME A 343 -15.217 -9.922 -35.755 1.00 0.00 H
> 
> However this still cause error after preprocessing:
> 
> ```
>  run_preprocess takes 50.503188371658325 seconds
> Traceback (most recent call last):
>   File "/ai2bmd/main.py", line 44, in <module>
>     prot = Protein(read_protein(preeq_pdb), pdb4params=preeq_nowat_pdb)
>   File "/ai2bmd/AIMD/protein.py", line 38, in __init__
>     self.generate_nonbonded_params()
>   File "/ai2bmd/AIMD/protein.py", line 157, in generate_nonbonded_params
>     pdb = PDBFile(self.nowater_PDB_path)
>   File "/opt/conda/lib/python3.9/site-packages/openmm/app/pdbfile.py", line 95, in __init__
>     pdb = PdbStructure(inputfile, load_all_models=True, extraParticleIdentifier=extraParticleIdentifier)
>   File "/opt/conda/lib/python3.9/site-packages/openmm/app/internal/pdbstructure.py", line 152, in __init__
>     self._load(input_stream)
>   File "/opt/conda/lib/python3.9/site-packages/openmm/app/internal/pdbstructure.py", line 164, in _load
>     self._add_atom(Atom(pdb_line, self, self.extraParticleIdentifier))
>   File "/opt/conda/lib/python3.9/site-packages/openmm/app/internal/pdbstructure.py", line 749, in __init__
>     raise ValueError('Misaligned residue name: %s' % pdb_line)
> ValueError: Misaligned residue name: ATOM       1  CH3 ACE    1      27.787  18.300  16.949
> ```

The following error occurs when I use a native amber24 preprocessor protein. How did you run it successfully? My water box size is 10A and the protein is 122 residues.

> /home/program/Amber24/amber24/bin/teLeap: Warning!
> The unperturbed charge of the unit (2.000000) is not zero.
> FATAL:  Atom .R<NME 122>.A<CH3 7> does not have a type.
> FATAL:  Atom .R<NME 122>.A<HH31 8> does not have a type.
> FATAL:  Atom .R<NME 122>.A<HH32 9> does not have a type.
> FATAL:  Atom .R<NME 122>.A<HH33 10> does not have a type.
