### ISSUE TITLE
'Broken pipe' and error out after 300ps of production run

### ISSUE THREAD

**Issue by Ruibin-Liu** [microsoft/AI2BMD#31]
Thanks for the wonderful project. I tried to run the example protein and also my own test system.
The simulation stopped around ~300ps in the production run. I checked the err file and found something concerning. For example this line 1172 for a C:
```
  1171  CA     641.906311   -435.589172   -513.264282     8  1170  1172  1175  1176
  1172  C  3818463.7500007260395.500000**************     9  1171  1173  1189
  1173  O      644.453003   -440.219360   -515.637512    11  1172
```
There are other atoms, mainly hydrogens, whose position (or velocity?) records have `***`.  

Some are not that bad but still 'wrong' for me, like:
```
  1377  C      653.576477   -448.168060   -504.604492    33  1372  1378  1379  1380
  1378  OH     653.337097   -448.922241   -503.797119    35  1377  1381
  1379  H  1782392.000000   -624.728760   -428.190735    34  1377
  1380  H      652.552368   -447.797516   -505.362213    34  1377
```
and
```
  2015  OH     657.122437   -429.164185   -527.046997    35  2014  2018
  2016  H      210.597610   -480.2626343561569.000000    34  2014
  2017  H      655.820312   -430.5732731781334.625000    34  2014
  2018  HO     657.960693   -428.557648   -526.905151    36  2015
```
Not sure what is the exact problem but looks like the 'old' stability issue for neural network force fileds.

**Comment by ElwynWang** [comment]
What protein was simulated, and how was the device and system setting?

**Comment by junqili** [comment]
Hello, I encountered the same problem. What caused it? And how can I solve it? 

> Thanks for the wonderful project. I tried to run the example protein and also my own test system. The simulation stopped around ~300ps in the production run. I checked the err file and found something concerning. For example this line 1172 for a C:
> 
> ```
>   1171  CA     641.906311   -435.589172   -513.264282     8  1170  1172  1175  1176
>   1172  C  3818463.7500007260395.500000**************     9  1171  1173  1189
>   1173  O      644.453003   -440.219360   -515.637512    11  1172
> ```
> 
> There are other atoms, mainly hydrogens, whose position (or velocity?) records have `***`.
> 
> Some are not that bad but still 'wrong' for me, like:
> 
> ```
>   1377  C      653.576477   -448.168060   -504.604492    33  1372  1378  1379  1380
>   1378  OH     653.337097   -448.922241   -503.797119    35  1377  1381
>   1379  H  1782392.000000   -624.728760   -428.190735    34  1377
>   1380  H      652.552368   -447.797516   -505.362213    34  1377
> ```
> 
> and
> 
> ```
>   2015  OH     657.122437   -429.164185   -527.046997    35  2014  2018
>   2016  H      210.597610   -480.2626343561569.000000    34  2014
>   2017  H      655.820312   -430.5732731781334.625000    34  2014
>   2018  HO     657.960693   -428.557648   -526.905151    36  2015
> ```
> 
> Not sure what is the exact problem but looks like the 'old' stability issue for neural network force fileds.
