### ISSUE TITLE
Will you release the pretrained model on PCQM4Mv2?

### ISSUE THREAD

**Issue by chengfengke** [microsoft/AI2BMD#33]
I notice that you don't release the pretrained checkpoint on PCQM4Mv2, will you release that?

**Comment by chengfengke** [comment]
If you can，would you mind send it to chengfengke@bupt.edu.cn,
We would like to try it very much,
thx for your novelty work.

**Comment by ElwynWang** [comment]
https://github.com/microsoft/AI2BMD/tree/OGB-LSC%40NIPS2022/checkpoints/Pretrained_3D_ViSNet_ckpt
