### ISSUE TITLE
Can I use this software to simulate graphene?

### ISSUE THREAD

**Issue by sssun826804236** [microsoft/AI2BMD#34]
Hi developer，
Can I use this software to simulate graphene? For example, calculate the potential energy between two layers of graphene, just like LAMMPS.

**Comment by ElwynWang** [comment]
AI2BMD is designed for biomolecular simulation, where "B" stands for biomolecules. We don't have plan to specifically design for materials, but AI2BMD framework support efficient simulations for any kinds of molecules including materials without fragmentation (see advanced setup in README).

**Comment by sssun826804236** [comment]
Thanks for your reply. I'll give it a try.
