### ISSUE TITLE
Can it be installed using conda?

### ISSUE THREAD

**Issue by XIANZHE-LI** [microsoft/AI2BMD#36]
Since my server itself is a Docker container, I cannot install and invoke Docker within it. The usual method of installing Docker doesn't work. Are there any other installation methods available?

**Comment by ElwynWang** [comment]
Considering the compiling and installation procedures are very complex, to ensure users with different backgrounds to use it smoothly, currently we provide the Docker for quick setup. We'll discuss the possibility for other installation ways in the future.
