### ISSUE TITLE
How do I change the src/AIMD/preprocess.py file and make it run successfully?

### ISSUE THREAD

**Issue by Lyueyang2020** [microsoft/AI2BMD#37]
First of all, thank you very much for your excellent work! I would like to ask you a simple question since I lack docker basics. When I download your entire project locally, after modifying only my local src/AIMD/preprocess.py (pmemd.cuda), it's still the initial preprocess.py (sander) that is run using docker. I'm not quite sure how to run the Docker container pointing to my modified preprocess.py file 
e.g. the command 

> docker cp c8e80ad4aacf:/path/to/container/file.txt /path/to/local/directory/

Because I'm not quite sure about container folder path. 
Thank you for your answer!

**Comment by bi-ran** [comment]
you can pass `--src-dir /path/to/local/src/directory/` to the script to mount your local `src` directory with your changes
