### ISSUE TITLE
[Dataset Structure] Atom Level

### ISSUE THREAD

**Issue by HaokaiHong** [microsoft/AI2BMD#42]
Thank you for sharing the dataset!

I suppose that one .npz file contains multiple protein units but not at the atom level? 

For example, in AA_no_smd.npz, are there 1,036,220 items, and each item represents a protein consisting of 22 units?

If I have misunderstood the data, please correct me. If I am correct, I would like to ask whether the data set at the all-atom level will be made public.

Thank you again for your research!

**Comment by bi-ran** [comment]
the dataset is at the atom level. in your example, `AA_no_smd.npz` contains 1,036,220 units, each with 22 atoms.

**Comment by HaokaiHong** [comment]
Many thanks for your response!
