### ISSUE TITLE
Results Reproduction

### ISSUE THREAD

**Issue by ShihaoShao-GH** [microsoft/AI2BMD#8]
Many thanks to your awesome Geoformer which gave the community another solid, and insightful work. But unfortunately I encountered some results reproduction issue with it. 
I downloaded your energy_U0.ckpt and testing on it only gave me 0.0054 that is different from the number 0.0043 in your paper. I strictly followed the guide in this repo and the only thing that seems obvious different to me is that I used torch=1.10.0+cuda11.3. But I didn't feel like it would be the case leading to the issue. Can you give me some hints about this? Thanks in advance!

**Comment by v-shaoningli** [comment]
Hi Shihao,

Sorry for the delay. We rerun the inference process and could reproduce our results:
<img width="1409" alt="image" src="https://github.com/microsoft/AI2BMD/assets/108473158/1bab16c0-be2c-4a3c-af80-d6db98ba9976">

Maybe the cuda/torch version influences the final inference results.
Also u could retrain the Geoformer on QM9-energy U0 following the instructions in README.

Best,
Yusong and Shaoning

**Comment by ShihaoShao-GH** [comment]
> Hi Shihao,
> 
> Sorry for the delay. We rerun the inference process and could reproduce our results: <img alt="image" width="1409" src="https://private-user-images.githubusercontent.com/108473158/292392748-1bab16c0-be2c-4a3c-af80-d6db98ba9976.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMzIwNDEsIm5iZiI6MTcwMzIzMTc0MSwicGF0aCI6Ii8xMDg0NzMxNTgvMjkyMzkyNzQ4LTFiYWIxNmMwLWJlMmMtNGEzYy1hZjgwLWQ2ZGI5OGJhOTk3Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMlQwNzU1NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZDY5ZDRhNjU5NGY4YTJhMzliMmZlNzBlODc0YTdjZmY3MDVjYzkzYTYwZmM1ZGFkMmQxMTViZmQ1YzA5OWVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7xueX5P7yiAWR0BNDdPJapoIq04xTE7UGsJluLuw9Jg">
> 
> Maybe the cuda/torch version influences the final inference results. Also u could retrain the Geoformer on QM9-energy U0 following the instructions in README.
> 
> Best, Yusong and Shaoning

Thanks for the response! I will go create an exact same environment to see if everything works well.

**Comment by ShihaoShao-GH** [comment]
It works. Thanks for your help, Yusong and Shaoning!
