### ISSUE TITLE
failed to build an environment to run the geoformer model

### ISSUE THREAD

**Issue by LengyanReader** [microsoft/AI2BMD#9]
Regarding this version combination,  it can't be installed, is there a better one for installing?
<img width="407" alt="image" src="https://github.com/microsoft/AI2BMD/assets/10557968/c3e30c8c-9175-4bac-bc5f-3ed883cc83ba">

<img width="529" alt="5656677895f49b7dae643d60b975bf4" src="https://github.com/microsoft/AI2BMD/assets/10557968/f63714b0-c396-44fd-9ea3-0e13ad39080e">

**Comment by XJTUNR** [comment]
Hi [LengyanReader](https://github.com/LengyanReader),  

These are the official installation instructions for PyTorch. If you encounter any issues, it might be worth checking whether your GPU supports the version of CUDA you're trying to use. Additionally, I recommend trying out [`mamba`](https://mamba.readthedocs.io/en/latest/installation/mamba-installation.html) for installation, as it can often provide a smoother and faster installation experience.  

Best regards,
Yusong
